name: CI

on:
    push:
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: yarn

            - run: yarn lint

            - run: yarn test

    bump-version:
        name: 'Bump Version on main'
        runs-on: ubuntu-latest
        permissions: write-all
        needs: tests

        steps:
            - name: 'Checkout source code'
              uses: 'actions/checkout@v2'
              with:
                  ref: ${{ github.ref }}
            - name: 'cat package.json'
              run: cat ./package.json
            - name: 'Automated Version Bump'
              id: version-bump
              uses: 'phips28/gh-action-bump-version@master'
              with:
                  tag-prefix: 'v'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: 'cat package.json'
              run: cat ./package.json
            - name: 'Output Step'
              env:
                  NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
              run: echo "new tag $NEW_TAG"

    release:
        runs-on: ubuntu-latest
        needs: bump-version
        steps:
            - uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  release-type: node
                  package-name: ${{env.ACTION_NAME}}
                  command: github-release
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'
                  always-auth: true
            - run: yarn
            - run: yarn build
            - name: Pack package
              run: yarn pack
              id: pack
            - name: Publish package
              run: yarn publish ${{ steps.pack.outputs.tarballPath }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
            - name: tag stable versions
              if: ${{ steps.release.outputs.release_created }}
              run: |
                  git config user.name github-actions[bot]
                  git config user.email github-actions[bot]@users.noreply.github.com
                  git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
                  git tag -d stable || true
                  git push origin :stable || true
                  git tag -a stable -m "Last Stable Release"
                  git push origin stable
